services:
  - type: web
    name: viralverse-server
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "node server/index.js"
    autoDeploy: true
